version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm run build
      - ls
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  name: flow
